# Generated by Django 5.2.5 on 2025-08-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_category_tag_event_is_private_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_speaker',
            options={'verbose_name': 'Event Speaker', 'verbose_name_plural': 'Event Speakers'},
        ),
        migrations.AlterModelOptions(
            name='event_sponsor',
            options={'verbose_name': 'Event Sponsor', 'verbose_name_plural': 'Event Sponsors'},
        ),
        migrations.AlterUniqueTogether(
            name='event_speaker',
            unique_together={('event', 'speaker')},
        ),
        migrations.AlterUniqueTogether(
            name='event_sponsor',
            unique_together={('event', 'sponsor')},
        ),
    ]
